// Package tree renders a deterministic, sorted, gitignore-aware tree
// view of a directory.
//
// Mirrors src/logmind/core/tree_gen.py — specifically the Python
// fallback path (the `tree` binary is NOT invoked from Go even when
// present, so we never rely on system-provided output formatting). All
// trees come from the Go walker so consuming repos get identical
// output regardless of host OS.
//
// The renderer respects SPEC §1.4's three pattern sources, merged in
// that section's order:
//
//  1. logmind built-in defaults (DEFAULT_IGNORES in tree_gen.py)
//  2. patterns from the repo's .gitignore (with leading-"/" and
//     trailing-"/" trimmed)
//  3. file_structure.ignore_patterns from .logmind/config.yml, plus any
//     extras the caller supplies
//
// The merge is unconditional — a repository that names one pattern of
// its own keeps the built-in sixteen (#269). `!pattern` is honoured in
// every source, which is what keeps that from being a one-way door: a
// project that genuinely wants dist/ on its map writes `!dist`.
//
// Pattern matching is path-aware: a pattern like `site/.next` matches
// any path that traverses through site/.next, not just basenames.
// Resolution is POSITIONAL — the last rule in the merged list that
// matches decides, exactly as git does within a .gitignore — see
// IgnoreRules.Matches.
package tree

import (
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/thrillmade/logmind/internal/atomicio"
	"github.com/thrillmade/logmind/internal/config"
	"github.com/thrillmade/logmind/internal/gitcli"
)

// DefaultFileStructureDepth mirrors Python's DEFAULT_FILE_STRUCTURE_DEPTH.
// Used by the file-structure subcommand when --max-depth is omitted.
const DefaultFileStructureDepth = 2

// fileStructureTemplate is the canonical wrapper around the rendered
// tree, byte-identical to templates/file-structure.md.template.
//
// The Python template uses str.format and a {tree_output} placeholder;
// we substitute by string concatenation so we don't have to encode the
// raw markdown's "{" / "}" characters.
const fileStructureTemplateHead = "# File Structure\n" +
	"\n" +
	"This file is auto-generated by logmind to provide AI agents with current project structure.\n" +
	"\n" +
	"```\n"

const fileStructureTemplateTail = "\n```\n" +
	"\n" +
	"_Truncated at depth 2 (logmind v0.5.0+ default). For a deeper view, run\n" +
	"`logmind file-structure --write docs/file-structure.md --max-depth N` or\n" +
	"`logmind tree --max-depth 0` for the full tree._\n"

// Rule is one pattern from one of §1.4's three sources. Negate marks a
// `!pattern` entry, which re-includes a path an EARLIER rule excluded —
// "earlier" being load-bearing, since resolution is positional.
type Rule struct {
	Pattern string
	Negate  bool
}

// IgnoreRules is the merged pattern list in §1.4 source order — defaults,
// then .gitignore, then config. One ordered list rather than separate
// ignore/negate buckets so that `!` is parsed in exactly one place and no
// rule can be filed under the wrong source. ORDER IS THE SEMANTICS here:
// Matches resolves by position, so reordering this slice changes verdicts.
//
// Patterns are stored as raw strings; matching happens at the leaf via
// filepath.Match. Per rule we test three targets per item:
//  1. full repo-relative path (e.g. "site/.next/cache")
//  2. each path component individually
//  3. the basename
type IgnoreRules []Rule

// Matches reports whether the path should be excluded.
//
// relPath is the path relative to the tree root (forward-slash form).
// basename is the path's last component (extracted once by the caller
// since it's reused across pattern tests).
//
// Resolution is POSITIONAL LAST-MATCH-WINS: the last rule in the merged list
// that matches decides, and a `!pattern` only re-includes what a rule BEFORE
// it excluded. That is §1.4 as written — "a !pattern re-includes a path an
// earlier pattern excluded" — and it is what git does. Inside one .gitignore,
//
//	!important.log
//	*.log
//
// git reports `.gitignore:2:*.log` for important.log: ignored, because the
// negation sits earlier. Any rule that lets a negation win from anywhere in
// the list disagrees with git on that file, and leaves config with no way to
// re-exclude what .gitignore negated.
//
// This is only correct because the sources are RANKED CORRECTLY, and that
// depends on the built-in defaults being a source of their own
// (config.DefaultIgnorePatterns, seeded first by ResolveRules) rather than
// arriving as the config source. When DefaultConfig still seeded
// FileStructure.IgnorePatterns, a repository with no config file at all
// handed ResolveRules sixteen built-in patterns at the CONFIG source's
// position — so a positional resolver let that third-position `dist` outrank
// a `.gitignore` `!dist` the repository had written on purpose. The defect
// was the mis-ranked defaults, not the positional rule; see
// config.FileStructureConfig.IgnorePatterns.
//
// The whole list is scanned rather than short-circuiting on the first match:
// under last-match-wins the LAST matching rule is the answer, so an early
// match tells us nothing.
func (r IgnoreRules) Matches(relPath, basename string) bool {
	if len(r) == 0 {
		return false
	}
	var components []string
	if relPath != "" {
		components = strings.Split(relPath, "/")
	}
	ignored := false
	for _, rule := range r {
		if !rule.matches(relPath, basename, components) {
			continue
		}
		ignored = !rule.Negate
	}
	return ignored
}

// matches tests the rule's pattern against the full relative path, the
// basename, and each path component. `components` is relPath pre-split by
// the caller, since it is reused across every rule in the list.
//
// IMPORTANT: filepath.Match has subtly different semantics from
// Python's fnmatch.fnmatchcase — Go's `*` does NOT match `/`, Python's
// does. For the patterns logmind actually ships (DEFAULT_IGNORES +
// typical .gitignore), the divergence is invisible: every pattern is
// either segment-level (`*.pyc`, `__pycache__`) or fully literal with
// a slash (`site/.next`). The mismatch would only surface on an
// unusual pattern like `*foo*/bar` which doesn't appear in real use.
// Worth noting if a future config.yml adds patterns that cross slashes.
func (rule Rule) matches(relPath, basename string, components []string) bool {
	if ok, _ := filepath.Match(rule.Pattern, relPath); ok {
		return true
	}
	if ok, _ := filepath.Match(rule.Pattern, basename); ok {
		return true
	}
	for _, comp := range components {
		if ok, _ := filepath.Match(rule.Pattern, comp); ok {
			return true
		}
	}
	return false
}

// parseRules converts raw pattern strings into Rules, in order. A leading
// "!" marks a negation and is stripped.
//
// §1.4 introduces `!pattern` right after listing the three sources without
// naming one, so it is honoured in ALL of them — the config source included.
// That is the superset reading (protocol#89 is still open on whether the
// config source qualifies): if `!` is later restricted to .gitignore, a
// config `!dist` degrades to an unmatched literal, whereas shipping without
// it strands every repository that needs to see a default-ignored directory.
//
// The leading-/trailing-"/" trim is NOT applied here — §1.4 scopes it to the
// .gitignore source, and states plainly that a trailing slash matches
// nothing, so patterns are written without one.
func parseRules(patterns []string) []Rule {
	rules := make([]Rule, 0, len(patterns))
	for _, p := range patterns {
		negate := strings.HasPrefix(p, "!")
		if negate {
			p = p[1:]
		}
		if p == "" {
			continue
		}
		rules = append(rules, Rule{Pattern: p, Negate: negate})
	}
	return rules
}

// readGitignoreRules returns the rules from `<repoRoot>/.gitignore` in file
// order. Strips comments, blank lines, leading "/" and trailing "/" —
// §1.4's trim, which this source and only this source gets.
//
// Mirrors Python _read_gitignore_patterns (tree_gen.py:80-109). Not a
// complete gitignore parser — anchored patterns / recursive globs are
// out of scope. Good enough to suppress obvious build-cache noise.
func readGitignoreRules(repoRoot string) ([]Rule, error) {
	path := filepath.Join(repoRoot, ".gitignore")
	data, readErr := os.ReadFile(path)
	if readErr != nil {
		if os.IsNotExist(readErr) {
			return nil, nil
		}
		return nil, readErr
	}
	var rules []Rule
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		negate := strings.HasPrefix(line, "!")
		if negate {
			line = line[1:]
		}
		line = strings.TrimPrefix(line, "/")
		line = strings.TrimSuffix(line, "/")
		if line == "" {
			continue
		}
		rules = append(rules, Rule{Pattern: line, Negate: negate})
	}
	return rules, nil
}

// ResolveRules merges §1.4's three pattern sources into the ordered rule
// list Render and repomap walk with. It is the ONE place the merge happens,
// so every consumer of file_structure.ignore_patterns gets the same answer:
//
//  1. the built-in defaults, unconditionally — a repository that names one
//     pattern of its own keeps the other sixteen. Before #269 they arrived
//     as this function's first argument, so a config that set the key at all
//     replaced them (yaml.Unmarshal overwrites a slice, it does not append)
//     and node_modules/, dist/ and .venv/ reappeared in the generated map.
//     They now come from config.DefaultIgnorePatterns — their OWN source,
//     not a copy that DefaultConfig smuggled into the config field. That
//     distinction is what makes positional resolution safe: with the
//     defaults ranked first, a `.gitignore` `!dist` in a repository that
//     configured nothing has nothing after it to override the re-inclusion.
//  2. the repository's .gitignore, leading/trailing "/" trimmed.
//  3. configPatterns — file_structure.ignore_patterns as loaded from
//     .logmind/config.yml — then any caller extras. `extras` is for ad-hoc
//     additions on top, kept for parity with Python's `extra_ignore`
//     parameter on generate_tree.
//
// Sources are concatenated in §1.4's order and resolved positionally: the
// LAST matching rule decides (see Matches). So a later source can both
// re-include what an earlier one excluded and re-exclude what an earlier one
// negated, which is what §1.4's "an earlier pattern" means and what git does.
func ResolveRules(repoRoot string, configPatterns []string, extras ...string) (IgnoreRules, error) {
	rules := parseRules(config.DefaultIgnorePatterns())
	gitignore, err := readGitignoreRules(repoRoot)
	if err != nil {
		return nil, err
	}
	rules = append(rules, gitignore...)
	rules = append(rules, parseRules(configPatterns)...)
	rules = append(rules, parseRules(extras)...)
	return dedup(rules), nil
}

// dedup drops repeated rules — same pattern AND same polarity, so `dist`
// and `!dist` both survive. It keeps the LAST occurrence, not the first.
//
// That is not a style choice, it is what makes dedup verdict-preserving
// under last-match-wins. Only the last rule matching a path decides, so
// deleting an EARLIER exact duplicate can never change any verdict: the
// later copy is still there, in the same place, and every rule after it is
// untouched. Keeping the first instead would move a rule earlier in the
// list and change answers — a .gitignore reading
//
//	*.log
//	!important.log
//	*.log
//
// resolves important.log as ignored (git agrees: last line wins), but
// first-seen dedup drops the third line and leaves `!important.log` last,
// flipping the verdict. Keep-last has no such case.
func dedup(in []Rule) IgnoreRules {
	lastAt := make(map[Rule]int, len(in))
	for i, rule := range in {
		lastAt[rule] = i
	}
	out := make(IgnoreRules, 0, len(in))
	for i, rule := range in {
		if lastAt[rule] != i {
			continue
		}
		out = append(out, rule)
	}
	return out
}

// Render walks rootPath and returns a Unicode-tree formatted string.
//
// Output shape mirrors Python's _generate_fallback_tree:
//
//	rootname
//	├── a
//	│   └── b
//	└── c
//
// Sort order: directories first, then alphabetical (case-insensitive)
// — matches Python's `key=lambda p: (not p.is_dir(), p.name.lower())`.
//
// maxDepth=0 means "unbounded" in the CLI but Render takes a negative
// sentinel (-1) to mean unbounded; the CLI wires this internally. A
// positive maxDepth truncates the tree at that depth (root = depth 0).
//
// The last rule matching an entry decides: a negating one re-includes it,
// a plain one excludes it. Both are matched against the entry's
// repo-relative posix path (e.g. "site/.next/cache").
func Render(rootPath string, rules IgnoreRules, maxDepth int) (string, error) {
	return RenderWithLabel(rootPath, rules, maxDepth, "")
}

// RenderWithLabel is Render with an explicit root label. label=="" reproduces
// Render's basename behavior EXACTLY (byte-parity with v0.6.14). A non-empty
// label makes the root line deterministic across checkouts/worktrees —
// fixing the churn where /tmp/foo and /work/logmind-pr otherwise produced
// different first lines (and thus a perpetually-"stale" file-structure.md).
func RenderWithLabel(rootPath string, rules IgnoreRules, maxDepth int, label string) (string, error) {
	rootPath = filepath.Clean(rootPath)
	rootName := label
	if rootName == "" {
		rootName = filepath.Base(rootPath)
		if rootName == "" || rootName == "/" {
			rootName = "."
		}
	}
	var b strings.Builder
	b.WriteString(rootName)
	// Depth 0 = root itself. If maxDepth == 0 (positive zero meaning
	// "root only"), no children render. The CLI translates --max-depth 0
	// to -1 (unbounded) BEFORE calling Render — so positive 0 here means
	// "stop". This matches the Python check `_current_depth >= max_depth`
	// which would short-circuit at depth 0 when max_depth==0.
	if maxDepth == 0 {
		return b.String(), nil
	}
	if err := walk(&b, rootPath, rootPath, "", rules, maxDepth, 0); err != nil {
		return "", err
	}
	return b.String(), nil
}

// walk is the recursive helper. `repoRoot` is the original root passed
// to Render (used to compute repo-relative paths for pattern matching).
// `prefix` is the indentation accumulated from parent frames.
//
// maxDepth: -1 = unbounded; >0 = truncate at this depth. depth is the
// current frame's depth (root = 0).
func walk(b *strings.Builder, repoRoot, dir, prefix string, rules IgnoreRules, maxDepth, depth int) error {
	if maxDepth >= 0 && depth >= maxDepth {
		return nil
	}
	dirEntries, err := os.ReadDir(dir)
	if err != nil {
		// Match Python: PermissionError + FileNotFoundError swallowed.
		// Anything else propagates so callers can decide.
		if os.IsPermission(err) || os.IsNotExist(err) {
			return nil
		}
		return err
	}

	// Sort: directories first, then alphabetical case-insensitive.
	// Match Python `(not p.is_dir(), p.name.lower())`.
	//
	// Python's `pathlib.Path.is_dir()` follows symlinks by default
	// (returns true for symlinks-to-directories). Go's
	// `os.DirEntry.IsDir()` uses lstat — returns FALSE for a symlink
	// even when its target is a directory. Use `isDirFollow` so the
	// sort matches Python on repos with symlinks-to-dirs.
	//
	// Loop safety is still preserved: walk() below checks ModeSymlink
	// on the resolved entry and skips recursion into symlinks.
	sort.SliceStable(dirEntries, func(i, j int) bool {
		ai, bi := isDirFollow(dir, dirEntries[i]), isDirFollow(dir, dirEntries[j])
		if ai != bi {
			return ai // true (is dir) sorts BEFORE false (file)
		}
		return strings.ToLower(dirEntries[i].Name()) < strings.ToLower(dirEntries[j].Name())
	})

	// Filter by ignore rules. We do this AFTER the sort so the
	// `is_last` connector pick still reflects the post-filter set.
	kept := make([]os.DirEntry, 0, len(dirEntries))
	for _, e := range dirEntries {
		full := filepath.Join(dir, e.Name())
		rel := relPosix(repoRoot, full)
		if rules.Matches(rel, e.Name()) {
			continue
		}
		kept = append(kept, e)
	}

	for i, e := range kept {
		isLast := i == len(kept)-1
		connector := "├── "
		nextPrefix := "│   "
		if isLast {
			connector = "└── "
			nextPrefix = "    "
		}
		b.WriteByte('\n')
		b.WriteString(prefix)
		b.WriteString(connector)
		b.WriteString(e.Name())
		if !e.IsDir() {
			continue
		}
		// Skip symlinks-to-directories to avoid loops. Match Python's
		// `if item.is_dir() and not item.is_symlink()` guard. We probe
		// via Info() rather than DirEntry.Type() because Type() returns
		// the EXACT entry type — a symlink IS marked as such, so we
		// read mode bits to be defensive.
		if info, err := e.Info(); err == nil && info.Mode()&os.ModeSymlink != 0 {
			continue
		}
		if err := walk(b, repoRoot, filepath.Join(dir, e.Name()), prefix+nextPrefix, rules, maxDepth, depth+1); err != nil {
			return err
		}
	}
	return nil
}

// relPosix returns full's repoRoot-relative path in posix form. Used
// for pattern matching where Windows backslashes would otherwise miss
// patterns like "site/.next".
func relPosix(repoRoot, full string) string {
	rel, err := filepath.Rel(repoRoot, full)
	if err != nil {
		return filepath.Base(full)
	}
	return filepath.ToSlash(rel)
}

// GenerateFileStructure wraps Render with the file-structure.md
// template, byte-identical to Python's generate_file_structure.
//
// repoRoot defaults to "." when empty.
// maxDepth=-1 → unbounded; 0 → root-only; positive → truncate.
//
// The function loads `<repoRoot>/.logmind/config.yml` for the config
// pattern source, which ResolveRules merges ON TOP of the built-in
// defaults and .gitignore rather than in place of them (§1.4). A missing
// or unparseable config degrades to the defaults alone — matches Python's
// load_config fallback.
func GenerateFileStructure(repoRoot string, maxDepth int) (string, error) {
	if repoRoot == "" {
		repoRoot = "."
	}
	cfg, _ := config.Load(repoRoot)
	rules, err := ResolveRules(repoRoot, cfg.FileStructure.IgnorePatterns)
	if err != nil {
		return "", err
	}
	tree, err := RenderWithLabel(repoRoot, rules, maxDepth, resolveRootLabel(repoRoot, cfg.FileStructure.RootLabel))
	if err != nil {
		return "", err
	}
	return fileStructureTemplateHead + tree + fileStructureTemplateTail, nil
}

// resolveRootLabel maps the config value to the literal root label.
//
// Empty (default, unconfigured) → the repository's actual name, derived
// from git's shared common-dir (gitcli.CommonDirRepoName) rather than the
// checkout directory's basename. In an ordinary top-level clone the two
// are identical, so this is byte-parity-preserving there; the divergence
// only shows up in a `git worktree` checkout, where the basename is
// something like "agent-<id>" but the common-dir-derived name is still the
// real repo. Falls back to "" (RenderWithLabel then uses the checkout
// basename) when repoRoot isn't a git repo at all — a plain non-git
// directory still works, no error.
//
// "auto" (explicit opt-in, pre-existing) → the git remote repo name, or ""
// when it can't be resolved (shallow/fork CI, no origin) so it degrades to
// the basename. Any other value is used verbatim — an explicit configured
// label always wins over both derivations above.
func resolveRootLabel(repoRoot, configured string) string {
	if configured == "auto" {
		return gitcli.RemoteRepoName(repoRoot)
	}
	if configured == "" {
		return gitcli.CommonDirRepoName(repoRoot)
	}
	return configured
}

// WriteFileStructure atomically writes the rendered file-structure to
// targetPath. Returns (changed, error) where changed=false means the
// file content was already up to date.
//
// Mirror of Python write_file_structure (tree_gen.py:323-357).
func WriteFileStructure(targetPath, repoRoot string, maxDepth int) (bool, error) {
	if repoRoot == "" {
		// Heuristic from Python: assume targetPath is <repo>/docs/file-structure.md.
		// If parent.parent doesn't look like a repo (no .git), fall through to cwd.
		abs, err := filepath.Abs(targetPath)
		if err != nil {
			return false, err
		}
		repoRoot = filepath.Dir(filepath.Dir(abs))
	}
	rendered, err := GenerateFileStructure(repoRoot, maxDepth)
	if err != nil {
		return false, err
	}
	existing, _ := os.ReadFile(targetPath)
	if string(existing) == rendered {
		return false, nil
	}
	// atomicio.WriteFile replaces a hand-rolled temp+rename that wrote to
	// the PREDICTABLE name targetPath+".tmp" with a bare os.WriteFile. Two
	// bugs in one: os.WriteFile follows symlinks, and the temp name was
	// guessable, so a dangling symlink planted at docs/file-structure.md.tmp
	// took the rendered tree straight outside the repository — and the
	// following os.Rename then renamed the LINK into place, leaving
	// file-structure.md itself pointing off-tree for every later write.
	// atomicio uses os.CreateTemp (unpredictable suffix, O_EXCL), does the
	// MkdirAll, and renames onto the destination NAME.
	if err := atomicio.WriteFile(targetPath, []byte(rendered), 0o644); err != nil {
		return false, err
	}
	return true, nil
}

// isDirFollow reports whether `entry` is (or symlinks to) a directory.
// Mirrors Python's `pathlib.Path.is_dir()` which follows symlinks by
// default. Used in sort comparisons so symlinks-to-directories sort
// with directories (Python-compatible) rather than with files
// (Go's lstat-based IsDir would do that).
//
// Walk-time recursion still guards on ModeSymlink to avoid loops —
// matching Python's `if item.is_dir() and not item.is_symlink()`.
func isDirFollow(parent string, entry os.DirEntry) bool {
	if entry.IsDir() {
		return true
	}
	if entry.Type()&os.ModeSymlink == 0 {
		return false
	}
	// Symlink. Follow it.
	info, err := os.Stat(filepath.Join(parent, entry.Name()))
	if err != nil {
		return false
	}
	return info.IsDir()
}
