// Package tree renders a deterministic, sorted, gitignore-aware tree
// view of a directory.
//
// Mirrors src/logmind/core/tree_gen.py — specifically the Python
// fallback path (the `tree` binary is NOT invoked from Go even when
// present, so we never rely on system-provided output formatting). All
// trees come from the Go walker so consuming repos get identical
// output regardless of host OS.
//
// The renderer respects three pattern sources, merged in this order:
//
//  1. logmind built-in defaults (DEFAULT_IGNORES in tree_gen.py)
//  2. patterns from the repo's .gitignore (with leading-"/" and
//     trailing-"/" trimmed; `!negate` lines are routed to the negate
//     bucket)
//  3. any extra patterns the caller supplies (e.g. config.yml's
//     file_structure.ignore_patterns)
//
// Pattern matching is path-aware: a pattern like `site/.next` matches
// any path that traverses through site/.next, not just basenames.
// Negation (`!keep.log`) re-includes a path that would otherwise be
// ignored — gitignore precedence rules.
package tree

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/thrillmade/logmind/internal/config"
)

// DefaultFileStructureDepth mirrors Python's DEFAULT_FILE_STRUCTURE_DEPTH.
// Used by the file-structure subcommand when --max-depth is omitted.
const DefaultFileStructureDepth = 2

// fileStructureTemplate is the canonical wrapper around the rendered
// tree, byte-identical to templates/file-structure.md.template.
//
// The Python template uses str.format and a {tree_output} placeholder;
// we substitute by string concatenation so we don't have to encode the
// raw markdown's "{" / "}" characters.
const fileStructureTemplateHead = "# File Structure\n" +
	"\n" +
	"This file is auto-generated by logmind to provide AI agents with current project structure.\n" +
	"\n" +
	"```\n"

const fileStructureTemplateTail = "\n```\n" +
	"\n" +
	"_Truncated at depth 2 (logmind v0.5.0+ default). For a deeper view, run\n" +
	"`logmind file-structure --write docs/file-structure.md --max-depth N` or\n" +
	"`logmind tree --max-depth 0` for the full tree._\n"

// IgnoreRules holds compiled ignore + negate patterns.
//
// Patterns are stored as raw strings; matching happens at the leaf via
// filepath.Match. Per pattern we test three targets per item:
//   1. full repo-relative path (e.g. "site/.next/cache")
//   2. each path component individually
//   3. the basename
//
// First match wins for ignore-vs-negate (negate beats ignore — matches
// gitignore precedence).
type IgnoreRules struct {
	Ignore []string
	Negate []string
}

// Matches reports whether the path should be excluded.
//
// relPath is the path relative to the tree root (forward-slash form).
// basename is the path's last component (extracted once by the caller
// since it's reused across pattern tests).
//
// Mirrors Python IgnoreRules.matches (tree_gen.py:47-59).
func (r IgnoreRules) Matches(relPath, basename string) bool {
	if !patternSetMatches(r.Ignore, relPath, basename) {
		return false
	}
	// Ignore matched — check negation override.
	if patternSetMatches(r.Negate, relPath, basename) {
		return false
	}
	return true
}

// patternSetMatches tests every pattern in `patterns` against the full
// relative path, each path component, and the basename. Returns true
// on the first match.
//
// Empty pattern set always returns false (matches Python's
// `if not patterns: return False` short-circuit).
//
// IMPORTANT: filepath.Match has subtly different semantics from
// Python's fnmatch.fnmatchcase — Go's `*` does NOT match `/`, Python's
// does. For the patterns logmind actually ships (DEFAULT_IGNORES +
// typical .gitignore), the divergence is invisible: every pattern is
// either segment-level (`*.pyc`, `__pycache__`) or fully literal with
// a slash (`site/.next`). The mismatch would only surface on an
// unusual pattern like `*foo*/bar` which doesn't appear in real use.
// Worth noting if a future config.yml adds patterns that cross slashes.
func patternSetMatches(patterns []string, relPath, basename string) bool {
	if len(patterns) == 0 {
		return false
	}
	var components []string
	if relPath != "" {
		components = strings.Split(relPath, "/")
	}
	for _, pat := range patterns {
		if ok, _ := filepath.Match(pat, relPath); ok {
			return true
		}
		if ok, _ := filepath.Match(pat, basename); ok {
			return true
		}
		for _, comp := range components {
			if ok, _ := filepath.Match(pat, comp); ok {
				return true
			}
		}
	}
	return false
}

// readGitignorePatterns returns (ignore, negate) lists from
// `<repoRoot>/.gitignore`. Strips comments, blank lines, leading "/"
// and trailing "/". `!pattern` entries are routed to negate.
//
// Mirrors Python _read_gitignore_patterns (tree_gen.py:80-109). Not a
// complete gitignore parser — anchored patterns / recursive globs are
// out of scope. Good enough to suppress obvious build-cache noise.
func readGitignorePatterns(repoRoot string) (ignore, negate []string, err error) {
	path := filepath.Join(repoRoot, ".gitignore")
	data, readErr := os.ReadFile(path)
	if readErr != nil {
		if os.IsNotExist(readErr) {
			return nil, nil, nil
		}
		return nil, nil, readErr
	}
	for _, raw := range strings.Split(string(data), "\n") {
		line := strings.TrimSpace(raw)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		isNegate := strings.HasPrefix(line, "!")
		if isNegate {
			line = line[1:]
		}
		line = strings.TrimPrefix(line, "/")
		line = strings.TrimSuffix(line, "/")
		if line == "" {
			continue
		}
		if isNegate {
			negate = append(negate, line)
		} else {
			ignore = append(ignore, line)
		}
	}
	return ignore, negate, nil
}

// ResolveRules merges built-in defaults + .gitignore patterns + caller
// extras into an IgnoreRules ready for Render.
//
// `defaults` should be config.DefaultConfig().FileStructure.IgnorePatterns
// (or the user-overridden equivalent). `extras` is for ad-hoc additions
// the caller wants on top — currently unused by the CLI but kept for
// parity with Python's `extra_ignore` parameter on generate_tree.
//
// Stable de-dup preserves first-seen order.
func ResolveRules(repoRoot string, defaults []string, extras ...string) (IgnoreRules, error) {
	combined := append([]string{}, defaults...)
	gi, neg, err := readGitignorePatterns(repoRoot)
	if err != nil {
		return IgnoreRules{}, err
	}
	combined = append(combined, gi...)
	combined = append(combined, extras...)

	rules := IgnoreRules{
		Ignore: dedup(combined),
		Negate: dedup(neg),
	}
	return rules, nil
}

func dedup(in []string) []string {
	seen := make(map[string]struct{}, len(in))
	out := make([]string, 0, len(in))
	for _, s := range in {
		if _, ok := seen[s]; ok {
			continue
		}
		seen[s] = struct{}{}
		out = append(out, s)
	}
	return out
}

// Render walks rootPath and returns a Unicode-tree formatted string.
//
// Output shape mirrors Python's _generate_fallback_tree:
//
//	rootname
//	├── a
//	│   └── b
//	└── c
//
// Sort order: directories first, then alphabetical (case-insensitive)
// — matches Python's `key=lambda p: (not p.is_dir(), p.name.lower())`.
//
// maxDepth=0 means "unbounded" in the CLI but Render takes a negative
// sentinel (-1) to mean unbounded; the CLI wires this internally. A
// positive maxDepth truncates the tree at that depth (root = depth 0).
//
// rules.Negate patterns re-include previously-matched paths; rules.Ignore
// excludes them. Both are matched against the entry's repo-relative
// posix path (e.g. "site/.next/cache").
func Render(rootPath string, rules IgnoreRules, maxDepth int) (string, error) {
	rootPath = filepath.Clean(rootPath)
	rootName := filepath.Base(rootPath)
	if rootName == "" || rootName == "/" {
		rootName = "."
	}
	var b strings.Builder
	b.WriteString(rootName)
	// Depth 0 = root itself. If maxDepth == 0 (positive zero meaning
	// "root only"), no children render. The CLI translates --max-depth 0
	// to -1 (unbounded) BEFORE calling Render — so positive 0 here means
	// "stop". This matches the Python check `_current_depth >= max_depth`
	// which would short-circuit at depth 0 when max_depth==0.
	if maxDepth == 0 {
		return b.String(), nil
	}
	if err := walk(&b, rootPath, rootPath, "", rules, maxDepth, 0); err != nil {
		return "", err
	}
	return b.String(), nil
}

// walk is the recursive helper. `repoRoot` is the original root passed
// to Render (used to compute repo-relative paths for pattern matching).
// `prefix` is the indentation accumulated from parent frames.
//
// maxDepth: -1 = unbounded; >0 = truncate at this depth. depth is the
// current frame's depth (root = 0).
func walk(b *strings.Builder, repoRoot, dir, prefix string, rules IgnoreRules, maxDepth, depth int) error {
	if maxDepth >= 0 && depth >= maxDepth {
		return nil
	}
	dirEntries, err := os.ReadDir(dir)
	if err != nil {
		// Match Python: PermissionError + FileNotFoundError swallowed.
		// Anything else propagates so callers can decide.
		if os.IsPermission(err) || os.IsNotExist(err) {
			return nil
		}
		return err
	}

	// Sort: directories first, then alphabetical case-insensitive.
	// Match Python `(not p.is_dir(), p.name.lower())`.
	sort.SliceStable(dirEntries, func(i, j int) bool {
		ai, bi := dirEntries[i].IsDir(), dirEntries[j].IsDir()
		if ai != bi {
			return ai // true (is dir) sorts BEFORE false (file)
		}
		return strings.ToLower(dirEntries[i].Name()) < strings.ToLower(dirEntries[j].Name())
	})

	// Filter by ignore rules. We do this AFTER the sort so the
	// `is_last` connector pick still reflects the post-filter set.
	kept := make([]os.DirEntry, 0, len(dirEntries))
	for _, e := range dirEntries {
		full := filepath.Join(dir, e.Name())
		rel := relPosix(repoRoot, full)
		if rules.Matches(rel, e.Name()) {
			continue
		}
		kept = append(kept, e)
	}

	for i, e := range kept {
		isLast := i == len(kept)-1
		connector := "├── "
		nextPrefix := "│   "
		if isLast {
			connector = "└── "
			nextPrefix = "    "
		}
		b.WriteByte('\n')
		b.WriteString(prefix)
		b.WriteString(connector)
		b.WriteString(e.Name())
		if !e.IsDir() {
			continue
		}
		// Skip symlinks-to-directories to avoid loops. Match Python's
		// `if item.is_dir() and not item.is_symlink()` guard. We probe
		// via Info() rather than DirEntry.Type() because Type() returns
		// the EXACT entry type — a symlink IS marked as such, so we
		// read mode bits to be defensive.
		if info, err := e.Info(); err == nil && info.Mode()&os.ModeSymlink != 0 {
			continue
		}
		if err := walk(b, repoRoot, filepath.Join(dir, e.Name()), prefix+nextPrefix, rules, maxDepth, depth+1); err != nil {
			return err
		}
	}
	return nil
}

// relPosix returns full's repoRoot-relative path in posix form. Used
// for pattern matching where Windows backslashes would otherwise miss
// patterns like "site/.next".
func relPosix(repoRoot, full string) string {
	rel, err := filepath.Rel(repoRoot, full)
	if err != nil {
		return filepath.Base(full)
	}
	return filepath.ToSlash(rel)
}

// GenerateFileStructure wraps Render with the file-structure.md
// template, byte-identical to Python's generate_file_structure.
//
// repoRoot defaults to "." when empty.
// maxDepth=-1 → unbounded; 0 → root-only; positive → truncate.
//
// The function loads `<repoRoot>/.logmind/config.yml` for the
// ignore_patterns override (falls back to built-in defaults when
// config is missing — matches Python's load_config fallback).
func GenerateFileStructure(repoRoot string, maxDepth int) (string, error) {
	if repoRoot == "" {
		repoRoot = "."
	}
	cfg, _ := config.Load(repoRoot)
	rules, err := ResolveRules(repoRoot, cfg.FileStructure.IgnorePatterns)
	if err != nil {
		return "", err
	}
	tree, err := Render(repoRoot, rules, maxDepth)
	if err != nil {
		return "", err
	}
	return fileStructureTemplateHead + tree + fileStructureTemplateTail, nil
}

// WriteFileStructure atomically writes the rendered file-structure to
// targetPath. Returns (changed, error) where changed=false means the
// file content was already up to date.
//
// Mirror of Python write_file_structure (tree_gen.py:323-357).
func WriteFileStructure(targetPath, repoRoot string, maxDepth int) (bool, error) {
	if repoRoot == "" {
		// Heuristic from Python: assume targetPath is <repo>/docs/file-structure.md.
		// If parent.parent doesn't look like a repo (no .git), fall through to cwd.
		abs, err := filepath.Abs(targetPath)
		if err != nil {
			return false, err
		}
		repoRoot = filepath.Dir(filepath.Dir(abs))
	}
	rendered, err := GenerateFileStructure(repoRoot, maxDepth)
	if err != nil {
		return false, err
	}
	existing, _ := os.ReadFile(targetPath)
	if string(existing) == rendered {
		return false, nil
	}
	if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
		return false, err
	}
	// Atomic-ish: write to .tmp, fsync, rename. Errors propagated.
	tmp := targetPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(rendered), 0o644); err != nil {
		return false, err
	}
	if err := os.Rename(tmp, targetPath); err != nil {
		return false, fmt.Errorf("rename tmp file: %w", err)
	}
	return true, nil
}
