package skill

import (
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestTitleCase pins the title-case behaviour against the Python
// `str.title()` reference. Each row was generated by running the
// snippet in CPython 3.13 — see the comment block in scaffold.go for
// the methodology.
func TestTitleCase(t *testing.T) {
	cases := []struct {
		In   string
		Want string
	}{
		{"my-test-skill", "My Test Skill"},
		{"sample", "Sample"},
		{"snake_case_name", "Snake Case Name"},
		{"A-B-C", "A B C"},
		{"foo--bar", "Foo  Bar"},
		{"_hidden", " Hidden"},
		{"a-b-c-1", "A B C 1"},
		{"abc123-def", "Abc123 Def"},
		{"foo3bar", "Foo3Bar"},
		{"3xyz", "3Xyz"},
		{"", ""},
	}
	for _, c := range cases {
		got := titleCase(c.In)
		if got != c.Want {
			t.Errorf("titleCase(%q) = %q; want %q", c.In, got, c.Want)
		}
	}
}

// TestScaffoldBasic_NoDescription confirms the default TODO text +
// title interpolation produce the Python byte image.
func TestScaffoldBasic_NoDescription(t *testing.T) {
	dir := t.TempDir()
	path, err := ScaffoldBasic(dir, "my-skill", "")
	if err != nil {
		t.Fatalf("ScaffoldBasic: %v", err)
	}
	body, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	got := string(body)
	if !strings.Contains(got, "name: my-skill") {
		t.Errorf("missing name; body:\n%s", got)
	}
	if !strings.Contains(got, "TODO: one-sentence trigger description for 'my-skill'") {
		t.Errorf("missing TODO description; body:\n%s", got)
	}
	if !strings.Contains(got, "# My Skill") {
		t.Errorf("title mis-rendered; body:\n%s", got)
	}
	if !strings.HasSuffix(got, "<!-- Concrete examples make skills easier to apply correctly. -->\n") {
		t.Errorf("missing trailing examples comment; tail:\n%q", got[len(got)-100:])
	}
}

// TestScaffoldBasic_RefusesClobber verifies the FileExistsError-style
// guard so a re-run doesn't overwrite hand-edited skills.
func TestScaffoldBasic_RefusesClobber(t *testing.T) {
	dir := t.TempDir()
	if _, err := ScaffoldBasic(dir, "twice", "first"); err != nil {
		t.Fatalf("first ScaffoldBasic: %v", err)
	}
	_, err := ScaffoldBasic(dir, "twice", "second")
	if !errors.Is(err, os.ErrExist) {
		t.Fatalf("second ScaffoldBasic err = %v; want os.ErrExist", err)
	}
}

// TestMDPath sanity-checks the canonical path layout.
func TestMDPath(t *testing.T) {
	got := MDPath("/repo", "thing")
	want := filepath.Join("/repo", ".claude", "skills", "thing", "SKILL.md")
	if got != want {
		t.Errorf("MDPath = %q; want %q", got, want)
	}
}
