"""Single-repo decision timeline (v0.2+).

Replaces the per-merge aggregator workflow (deleted in v0.2) with a
deterministic, conflict-free derived VIEW of all decisions across:

  - ``docs/decisions.md``                    (direct-on-main decisions, user-edited)
  - ``docs/decisions-branches/*.md``         (per-feature-branch decisions)
  - ``docs/decisions-archive.md``            (rotated-out older entries)

Sources stay user-owned. The derived artifact is a separate file —
``docs/timeline.md`` — that's regenerated by the CLI from these sources
on every PR's CI run. Two PRs in flight produce the SAME canonical
``timeline.md`` after rebase (same inputs → same output), so the file
can't conflict.

Two consumption modes:

  - Stdout view (``logmind timeline``):              human/agent reading
  - File regeneration (``logmind timeline --write``): CI step writes
    ``docs/timeline.md`` as a derived artifact, commits to PR branch
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import List, Optional

from logmind.core.parser import iter_decisions


@dataclass(frozen=True)
class TimelineEntry:
    """One decision, with provenance for dig-in."""

    date: datetime
    title: str
    source_path: Path        # relative to repo root
    source_label: str        # "main" / "feat/foo" / "archive"


# ---------------------------------------------------------------------------
# Collection
# ---------------------------------------------------------------------------


def _branch_label_from_filename(name: str) -> str:
    """Inverse of logger._sanitize_branch — recover a display label.

    `logger._sanitize_branch` replaces ``/``, ``\\``, ``:`` with ``__`` / ``_``;
    we can't perfectly reverse that, but ``feat__auth`` → ``feat/auth`` is the
    99% case so we apply it conservatively.
    """
    stem = name.removesuffix(".md")
    return stem.replace("__", "/")


def collect_entries(docs_path: Path) -> List[TimelineEntry]:
    """Collect every TimelineEntry from a logmind-installed docs/ directory.

    Sources walked (all read-only; the function never writes):

      docs/decisions.md                     → source_label="main"
      docs/decisions-archive.md             → source_label="archive"
      docs/decisions-branches/<branch>.md   → source_label="<branch>"

    The function tolerates missing files (returns the entries it can find).
    """
    entries: List[TimelineEntry] = []
    root = docs_path

    main_md = root / "decisions.md"
    if main_md.exists():
        for dt, title in iter_decisions(main_md):
            entries.append(
                TimelineEntry(
                    date=dt,
                    title=title,
                    source_path=main_md.relative_to(root.parent)
                    if root.parent.exists()
                    else Path("docs/decisions.md"),
                    source_label="main",
                )
            )

    archive_md = root / "decisions-archive.md"
    if archive_md.exists():
        for dt, title in iter_decisions(archive_md):
            entries.append(
                TimelineEntry(
                    date=dt,
                    title=title,
                    source_path=archive_md.relative_to(root.parent)
                    if root.parent.exists()
                    else Path("docs/decisions-archive.md"),
                    source_label="archive",
                )
            )

    branches_dir = root / "decisions-branches"
    if branches_dir.exists() and branches_dir.is_dir():
        for branch_file in sorted(branches_dir.glob("*.md")):
            label = _branch_label_from_filename(branch_file.name)
            for dt, title in iter_decisions(branch_file):
                entries.append(
                    TimelineEntry(
                        date=dt,
                        title=title,
                        source_path=branch_file.relative_to(root.parent)
                        if root.parent.exists()
                        else Path("docs/decisions-branches") / branch_file.name,
                        source_label=label,
                    )
                )

    entries.sort(key=lambda e: e.date, reverse=True)
    return entries


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


_TIMELINE_HEADER = (
    "# Decision Timeline\n"
    "\n"
    "**Auto-generated** — do not edit by hand. This is the high-level\n"
    "timeline across all decisions in this repo: direct-on-main entries,\n"
    "per-feature-branch logs in `docs/decisions-branches/`, and the\n"
    "archived rotations in `docs/decisions-archive.md`. The granular\n"
    "detail (reasoning, alternatives, implications) lives in the source\n"
    "file linked on each row — agents should dig in there as needed.\n"
    "\n"
    "Regenerated by `logmind timeline --write docs/decisions.md` on every\n"
    "PR's CI run, so this file is always coherent with current `main`.\n"
    "\n"
    "---\n"
)


def render_markdown(entries: List[TimelineEntry]) -> str:
    """Render entries as a markdown timeline grouped by year-month.

    Output shape:

        # Decision Timeline
        <header explaining derived-file nature>
        ---

        ## 2026-05

        - **2026-05-15** — site: footer polish — version, skill URL, breathing room… *(main)* — [docs/decisions.md](docs/decisions.md)
        - **2026-05-15** — v0.1.4: optional LOGMIND_BOT_PAT for aggregator PRs *(feat/v0.1.4-bot-pat-fallback)* — [docs/decisions-branches/feat__v0.1.4-bot-pat-fallback.md](...)

        ## 2026-04
        ...
    """
    if not entries:
        return _TIMELINE_HEADER + "\n*(no decisions logged yet)*\n"

    lines = [_TIMELINE_HEADER, ""]
    last_month: Optional[str] = None
    for e in entries:
        month = e.date.strftime("%Y-%m")
        if month != last_month:
            if last_month is not None:
                lines.append("")
            lines.append(f"## {month}")
            lines.append("")
            last_month = month
        link_label = str(e.source_path).replace("\\", "/")
        lines.append(
            f"- **{e.date.strftime('%Y-%m-%d')}** — {e.title} "
            f"*({e.source_label})* — [{link_label}]({link_label})"
        )
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Public API used by CLI
# ---------------------------------------------------------------------------


def generate_timeline(docs_path: Optional[Path] = None) -> str:
    """Collect every decision under docs_path and return the rendered markdown."""
    if docs_path is None:
        docs_path = Path.cwd() / "docs"
    entries = collect_entries(docs_path)
    return render_markdown(entries)


def write_timeline(
    target_path: Path,
    docs_path: Optional[Path] = None,
) -> bool:
    """Regenerate target_path's content from sources.

    Returns True if the file changed (caller can use this as a CI signal
    to know whether to commit). False if content was already up to date.
    """
    rendered = generate_timeline(docs_path)
    existing = target_path.read_text(encoding="utf-8") if target_path.exists() else ""
    if existing == rendered:
        return False
    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(rendered, encoding="utf-8")
    return True
