// Package timeline renders the decision timeline.
//
// As of v2.0.0 there is exactly ONE assembly model: main-canonical, the
// §1.6.4 deterministic source-derived union (see canonical.go). The old
// branch-divergent brief/full renderer — a Python-parity artifact — was
// removed once the Python era retired; main-canonical is now the sole,
// unconditional timeline.
//
// This file holds only the shared rendered-file scaffolding (the header
// preface + the empty-body sentinel) that renderCanonical consumes.
package timeline

// header is the canonical preface for the rendered file.
//
// Pulled out as a const so every render path shares one exact preamble.
// The trailing "---" + newline is included; renderCanonical then appends
// one blank line before the first month header.
const header = `# Decision Timeline

**Auto-generated** — do not edit by hand. This is the high-level
timeline across all decisions in this repo: direct-on-main entries,
per-feature-branch logs in ` + "`docs/decisions-branches/`" + `, and the
archived rotations in ` + "`docs/decisions-archive.md`" + `. The granular
detail (reasoning, alternatives, implications) lives in the source
file linked on each row — agents should dig in there as needed.

Regenerated by ` + "`logmind timeline --write docs/timeline.md`" + ` on every
PR's CI run, so this file is always coherent with current ` + "`main`" + `.

---
`

// emptyBody is what the renderer returns when no entries are present.
const emptyBody = "\n*(no decisions logged yet)*\n"
