// Package timeline renders the decision timeline.
//
// As of v2.0.0 there is exactly ONE assembly model: main-canonical, the
// §1.6.4 deterministic source-derived union (see canonical.go). The old
// branch-divergent brief/full renderer — a Python-parity artifact — was
// removed once the Python era retired; main-canonical is now the sole,
// unconditional timeline.
//
// This file holds only the shared rendered-file scaffolding (the two header
// prefaces + their empty-body sentinels) that renderCanonical consumes.
package timeline

// RecentLimit is the SPEC §3.3 bound: docs/timeline.md carries this many
// entries, newest first, and everything older renders to
// docs/timeline-archive.md.
//
// It is a RENDERING parameter, not a capacity. Both files are produced from
// one read of the branch files on every regeneration (Generate), so moving
// this number changes only where the two renderings are cut — no entry is
// transferred, consumed, or handed over, and nothing has to be migrated. See
// generateAt, which is this constant's only consumer.
const RecentLimit = 50

// header is the canonical preface for docs/timeline.md.
//
// Pulled out as a const so every render path shares one exact preamble.
// The trailing "---" + newline is included; renderCanonical then appends
// one blank line before the first month header.
const header = `# Decision Timeline

**Auto-generated** — do not edit by hand. This is the high-level
timeline across all decisions in this repo, drawn from the per-branch
logs in ` + "`docs/decisions-branches/`" + `. The granular detail
(reasoning, alternatives, implications) lives in the source file linked
on each row — agents should dig in there as needed.

This file carries the 50 most recent entries; the history continues in
[docs/timeline-archive.md](timeline-archive.md), same format, same
rules. Both are rendered from the same sources on every regeneration —
nothing is moved between them.

Regenerated by ` + "`logmind timeline --write docs/timeline.md`" + ` on every
PR's CI run, so this file is always coherent with current ` + "`main`" + `.

---
`

// archiveHeader is the canonical preface for docs/timeline-archive.md — the
// continuation of docs/timeline.md, in the same format under the same rules
// (§3.3), so a reader who reaches the end of one carries straight on here.
const archiveHeader = `# Decision Timeline — Archive

**Auto-generated** — do not edit by hand. This continues
[docs/timeline.md](timeline.md), which carries the 50 most recent
entries; everything older is here, in the same format under the same
rules.

Nothing was moved to produce this file. Both it and ` + "`docs/timeline.md`" + `
are rendered from ` + "`docs/decisions-branches/`" + ` on every regeneration —
the split is a rendering choice, and the record behind it is unbounded.

Regenerated by ` + "`logmind timeline --write docs/timeline-archive.md --half archive`" + `
on every PR's CI run, so this file is always coherent with current ` + "`main`" + `.
Each file is written by the command that names it — ` + "`--write`" + ` never
writes a file it was not given.

---
`

// emptyBody is what the renderer returns when no entries are present.
const emptyBody = "\n*(no decisions logged yet)*\n"

// emptyArchiveBody is the archive's own sentinel: an archive with no rows is
// the normal state of a repository whose whole history still fits in
// docs/timeline.md, not an empty record.
const emptyArchiveBody = "\n*(nothing older yet — the whole history fits in [docs/timeline.md](timeline.md))*\n"
