# installer/cask-template.rb — REFERENCE shape of the Homebrew cask
# that GoReleaser auto-generates and PRs into thrillmade/homebrew-tap.
#
# This file is NOT consumed by GoReleaser. It exists to document what the
# generated cask at thrillmade/homebrew-tap/Casks/logmind.rb looks like,
# so reviewers can sanity-check the auto-bump output without cloning the
# tap repo.
#
# The actual cask is generated by GoReleaser from the `homebrew_casks:`
# block in /.goreleaser.yaml using its built-in Ruby templates. To tweak
# the cask shape, edit .goreleaser.yaml — NOT this file.
#
# To preview what GoReleaser would generate locally:
#   goreleaser release --snapshot --clean --skip=publish,sign,notarize
#   cat dist/homebrew/Casks/logmind.rb
#
# Example output for tag v1.0.0:

cask "logmind" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "<sha-of-darwin-x86_64-tarball>"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "<sha-of-darwin-arm64-tarball>"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "<sha-of-linux-x86_64-tarball>"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "<sha-of-linux-arm64-tarball>"
      url "https://github.com/thrillmade/logmind/releases/download/v#{version}/logmind_#{version}_linux_arm64.tar.gz"
    end
  end

  name "logmind"
  desc "Decision logging for AI-assisted development — branch-aware by default."
  homepage "https://logmind.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "logmind"

  # Post-install: strip macOS quarantine xattr. Belt-and-braces — the
  # binary is codesigned + notarized, but tarballs downloaded by brew
  # sometimes inherit the quarantine attribute. Stripping it here
  # avoids Gatekeeper's "this developer cannot be verified" dialog
  # the first time the binary runs on a fresh machine.
  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/logmind"]
    end
  end
end
